spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
        cache: false
        mode: LEGACYHTML5