management:
  security:
    enabled: false
  server:
    port: 8081 # springboot 2.0+   £¬µÍ°æ±¾ÊÇ£º management.port


info:
  aaa:
    name: luffy
    email: luffy7855@gmail.com
  bbb:
    age: 25
    hobbies: running
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"
